version: '3'
services:
  node:
    image: express
    build: .
    ports:
      - ${PORT_HOST}:${PORT}
    depends_on:
      - db
    restart: always
    environment:
      - PORT=${PORT}
    volumes:
      - ./logs:/usr/app/logs
      - ./src:/usr/app/src
    networks:
      - net
  db:
    image: postgres
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - net
networks:
  net:
    driver: bridge
